import { db } from '@/db';
import { bookings } from '@/db/schema';

async function main() {
    const now = new Date();
    const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    
    const sampleBookings = [
        // Completed bookings (1-12)
        {
            customerId: 4,
            driverId: 12,
            pickupLocation: 'Bandra West, Mumbai',
            pickupLat: 19.0596,
            pickupLng: 72.8295,
            dropoffLocation: 'Andheri East, Mumbai',
            dropoffLat: 19.1136,
            dropoffLng: 72.8697,
            vehicleType: 'sedan',
            status: 'completed',
            fareEstimate: 15.0,
            finalFare: 16.5,
            paymentMethod: 'upi',
            paymentStatus: 'completed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 1 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 1 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
            completionTime: new Date(thirtyDaysAgo.getTime() + 1 * 24 * 60 * 60 * 1000 + 40 * 60 * 1000).toISOString(),
        },
        {
            customerId: 5,
            driverId: 13,
            pickupLocation: 'Connaught Place, New Delhi',
            pickupLat: 28.6315,
            pickupLng: 77.2167,
            dropoffLocation: 'Dwarka Sector 21, New Delhi',
            dropoffLat: 28.5525,
            dropoffLng: 77.0622,
            vehicleType: 'mini',
            status: 'completed',
            fareEstimate: 22.0,
            finalFare: 20.5,
            paymentMethod: 'card',
            paymentStatus: 'completed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 3 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 3 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
            completionTime: new Date(thirtyDaysAgo.getTime() + 3 * 24 * 60 * 60 * 1000 + 55 * 60 * 1000).toISOString(),
        },
        {
            customerId: 6,
            driverId: 14,
            pickupLocation: 'Koramangala, Bangalore',
            pickupLat: 12.9352,
            pickupLng: 77.6245,
            dropoffLocation: 'Electronic City, Bangalore',
            dropoffLat: 12.8456,
            dropoffLng: 77.6603,
            vehicleType: 'suv',
            status: 'completed',
            fareEstimate: 18.0,
            finalFare: 19.8,
            paymentMethod: 'wallet',
            paymentStatus: 'completed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 5 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
            completionTime: new Date(thirtyDaysAgo.getTime() + 5 * 24 * 60 * 60 * 1000 + 35 * 60 * 1000).toISOString(),
        },
        {
            customerId: 7,
            driverId: 15,
            pickupLocation: 'Anna Nagar, Chennai',
            pickupLat: 13.0878,
            pickupLng: 80.2085,
            dropoffLocation: 'T Nagar, Chennai',
            dropoffLat: 13.0418,
            dropoffLng: 80.2341,
            vehicleType: 'auto',
            status: 'completed',
            fareEstimate: 8.0,
            finalFare: 8.5,
            paymentMethod: 'cash',
            paymentStatus: 'completed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 7 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
            completionTime: new Date(thirtyDaysAgo.getTime() + 7 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
        },
        {
            customerId: 8,
            driverId: 16,
            pickupLocation: 'Hitech City, Hyderabad',
            pickupLat: 17.4485,
            pickupLng: 78.3908,
            dropoffLocation: 'Banjara Hills, Hyderabad',
            dropoffLat: 17.4239,
            dropoffLng: 78.4738,
            vehicleType: 'sedan',
            status: 'completed',
            fareEstimate: 12.0,
            finalFare: 13.2,
            paymentMethod: 'upi',
            paymentStatus: 'completed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 10 * 24 * 60 * 60 * 1000 + 18 * 60 * 1000).toISOString(),
            completionTime: new Date(thirtyDaysAgo.getTime() + 10 * 24 * 60 * 60 * 1000 + 42 * 60 * 1000).toISOString(),
        },
        {
            customerId: 9,
            driverId: 17,
            pickupLocation: 'Salt Lake, Kolkata',
            pickupLat: 22.5726,
            pickupLng: 88.3639,
            dropoffLocation: 'Park Street, Kolkata',
            dropoffLat: 22.5549,
            dropoffLng: 88.3516,
            vehicleType: 'mini',
            status: 'completed',
            fareEstimate: 10.0,
            finalFare: 9.0,
            paymentMethod: 'card',
            paymentStatus: 'completed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 12 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 12 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
            completionTime: new Date(thirtyDaysAgo.getTime() + 12 * 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
        },
        {
            customerId: 10,
            driverId: 18,
            pickupLocation: 'MG Road, Pune',
            pickupLat: 18.5204,
            pickupLng: 73.8567,
            dropoffLocation: 'Hinjewadi, Pune',
            dropoffLat: 18.5913,
            dropoffLng: 73.7389,
            vehicleType: 'sedan',
            status: 'completed',
            fareEstimate: 25.0,
            finalFare: 27.5,
            paymentMethod: 'wallet',
            paymentStatus: 'completed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 14 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
            completionTime: new Date(thirtyDaysAgo.getTime() + 14 * 24 * 60 * 60 * 1000 + 50 * 60 * 1000).toISOString(),
        },
        {
            customerId: 11,
            driverId: 19,
            pickupLocation: 'Bandra West, Mumbai',
            pickupLat: 19.0596,
            pickupLng: 72.8295,
            dropoffLocation: 'Powai, Mumbai',
            dropoffLat: 19.1176,
            dropoffLng: 72.9060,
            vehicleType: 'suv',
            status: 'completed',
            fareEstimate: 20.0,
            finalFare: 22.0,
            paymentMethod: 'upi',
            paymentStatus: 'completed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 16 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 16 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
            completionTime: new Date(thirtyDaysAgo.getTime() + 16 * 24 * 60 * 60 * 1000 + 55 * 60 * 1000).toISOString(),
        },
        {
            customerId: 12,
            driverId: 12,
            pickupLocation: 'Connaught Place, New Delhi',
            pickupLat: 28.6315,
            pickupLng: 77.2167,
            dropoffLocation: 'Nehru Place, New Delhi',
            dropoffLat: 28.5494,
            dropoffLng: 77.2501,
            vehicleType: 'sedan',
            status: 'completed',
            fareEstimate: 14.0,
            finalFare: 15.4,
            paymentMethod: 'cash',
            paymentStatus: 'completed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 18 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 18 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
            completionTime: new Date(thirtyDaysAgo.getTime() + 18 * 24 * 60 * 60 * 1000 + 38 * 60 * 1000).toISOString(),
        },
        {
            customerId: 13,
            driverId: 13,
            pickupLocation: 'Koramangala, Bangalore',
            pickupLat: 12.9352,
            pickupLng: 77.6245,
            dropoffLocation: 'Whitefield, Bangalore',
            dropoffLat: 12.9698,
            dropoffLng: 77.7499,
            vehicleType: 'mini',
            status: 'completed',
            fareEstimate: 28.0,
            finalFare: 30.8,
            paymentMethod: 'card',
            paymentStatus: 'completed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 20 * 24 * 60 * 60 * 1000 + 22 * 60 * 1000).toISOString(),
            completionTime: new Date(thirtyDaysAgo.getTime() + 20 * 24 * 60 * 60 * 1000 + 65 * 60 * 1000).toISOString(),
        },
        {
            customerId: 4,
            driverId: 14,
            pickupLocation: 'Anna Nagar, Chennai',
            pickupLat: 13.0878,
            pickupLng: 80.2085,
            dropoffLocation: 'Velachery, Chennai',
            dropoffLat: 12.9757,
            dropoffLng: 80.2212,
            vehicleType: 'suv',
            status: 'completed',
            fareEstimate: 16.0,
            finalFare: 17.6,
            paymentMethod: 'wallet',
            paymentStatus: 'completed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 22 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 22 * 24 * 60 * 60 * 1000 + 18 * 60 * 1000).toISOString(),
            completionTime: new Date(thirtyDaysAgo.getTime() + 22 * 24 * 60 * 60 * 1000 + 48 * 60 * 1000).toISOString(),
        },
        {
            customerId: 5,
            driverId: 15,
            pickupLocation: 'Hitech City, Hyderabad',
            pickupLat: 17.4485,
            pickupLng: 78.3908,
            dropoffLocation: 'Secunderabad, Hyderabad',
            dropoffLat: 17.4399,
            dropoffLng: 78.4983,
            vehicleType: 'auto',
            status: 'completed',
            fareEstimate: 11.0,
            finalFare: 12.1,
            paymentMethod: 'upi',
            paymentStatus: 'completed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 24 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 24 * 24 * 60 * 60 * 1000 + 14 * 60 * 1000).toISOString(),
            completionTime: new Date(thirtyDaysAgo.getTime() + 24 * 24 * 60 * 60 * 1000 + 36 * 60 * 1000).toISOString(),
        },

        // In Progress bookings (13-17)
        {
            customerId: 6,
            driverId: 16,
            pickupLocation: 'Salt Lake, Kolkata',
            pickupLat: 22.5726,
            pickupLng: 88.3639,
            dropoffLocation: 'Howrah, Kolkata',
            dropoffLat: 22.5958,
            dropoffLng: 88.2636,
            vehicleType: 'sedan',
            status: 'in_progress',
            fareEstimate: 13.0,
            finalFare: null,
            paymentMethod: 'card',
            paymentStatus: 'pending',
            bookingTime: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 18 * 60 * 1000).toISOString(),
            completionTime: null,
        },
        {
            customerId: 7,
            driverId: 17,
            pickupLocation: 'MG Road, Pune',
            pickupLat: 18.5204,
            pickupLng: 73.8567,
            dropoffLocation: 'Kothrud, Pune',
            dropoffLat: 18.5074,
            dropoffLng: 73.8077,
            vehicleType: 'mini',
            status: 'in_progress',
            fareEstimate: 9.0,
            finalFare: null,
            paymentMethod: 'upi',
            paymentStatus: 'pending',
            bookingTime: new Date(now.getTime() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(now.getTime() - 1.5 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
            completionTime: null,
        },
        {
            customerId: 8,
            driverId: 18,
            pickupLocation: 'Bandra West, Mumbai',
            pickupLat: 19.0596,
            pickupLng: 72.8295,
            dropoffLocation: 'Colaba, Mumbai',
            dropoffLat: 18.9067,
            dropoffLng: 72.8147,
            vehicleType: 'sedan',
            status: 'in_progress',
            fareEstimate: 24.0,
            finalFare: null,
            paymentMethod: 'wallet',
            paymentStatus: 'pending',
            bookingTime: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
            completionTime: null,
        },
        {
            customerId: 9,
            driverId: 19,
            pickupLocation: 'Connaught Place, New Delhi',
            pickupLat: 28.6315,
            pickupLng: 77.2167,
            dropoffLocation: 'Gurgaon Cyber City',
            dropoffLat: 28.4950,
            dropoffLng: 77.0890,
            vehicleType: 'suv',
            status: 'in_progress',
            fareEstimate: 32.0,
            finalFare: null,
            paymentMethod: 'cash',
            paymentStatus: 'pending',
            bookingTime: new Date(now.getTime() - 12 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(now.getTime() - 12 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
            completionTime: null,
        },
        {
            customerId: 10,
            driverId: 12,
            pickupLocation: 'Koramangala, Bangalore',
            pickupLat: 12.9352,
            pickupLng: 77.6245,
            dropoffLocation: 'Indiranagar, Bangalore',
            dropoffLat: 12.9716,
            dropoffLng: 77.6412,
            vehicleType: 'sedan',
            status: 'in_progress',
            fareEstimate: 7.0,
            finalFare: null,
            paymentMethod: 'card',
            paymentStatus: 'pending',
            bookingTime: new Date(now.getTime() - 6 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(now.getTime() - 6 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
            completionTime: null,
        },

        // Pending bookings (18-21)
        {
            customerId: 11,
            driverId: null,
            pickupLocation: 'Anna Nagar, Chennai',
            pickupLat: 13.0878,
            pickupLng: 80.2085,
            dropoffLocation: 'OMR, Chennai',
            dropoffLat: 12.8466,
            dropoffLng: 80.2206,
            vehicleType: 'mini',
            status: 'pending',
            fareEstimate: 26.0,
            finalFare: null,
            paymentMethod: 'upi',
            paymentStatus: 'pending',
            bookingTime: new Date(now.getTime() - 3 * 60 * 60 * 1000).toISOString(),
            pickupTime: null,
            completionTime: null,
        },
        {
            customerId: 12,
            driverId: null,
            pickupLocation: 'Hitech City, Hyderabad',
            pickupLat: 17.4485,
            pickupLng: 78.3908,
            dropoffLocation: 'Kukatpally, Hyderabad',
            dropoffLat: 17.4849,
            dropoffLng: 78.3914,
            vehicleType: 'sedan',
            status: 'pending',
            fareEstimate: 15.0,
            finalFare: null,
            paymentMethod: 'wallet',
            paymentStatus: 'pending',
            bookingTime: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
            pickupTime: null,
            completionTime: null,
        },
        {
            customerId: 13,
            driverId: null,
            pickupLocation: 'Salt Lake, Kolkata',
            pickupLat: 22.5726,
            pickupLng: 88.3639,
            dropoffLocation: 'Dum Dum, Kolkata',
            dropoffLat: 22.6540,
            dropoffLng: 88.4261,
            vehicleType: 'auto',
            status: 'pending',
            fareEstimate: 12.0,
            finalFare: null,
            paymentMethod: 'cash',
            paymentStatus: 'pending',
            bookingTime: new Date(now.getTime() - 1 * 60 * 60 * 1000).toISOString(),
            pickupTime: null,
            completionTime: null,
        },
        {
            customerId: 4,
            driverId: null,
            pickupLocation: 'MG Road, Pune',
            pickupLat: 18.5204,
            pickupLng: 73.8567,
            dropoffLocation: 'Wakad, Pune',
            dropoffLat: 18.5974,
            dropoffLng: 73.7898,
            vehicleType: 'suv',
            status: 'pending',
            fareEstimate: 19.0,
            finalFare: null,
            paymentMethod: 'card',
            paymentStatus: 'pending',
            bookingTime: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
            pickupTime: null,
            completionTime: null,
        },

        // Cancelled bookings (22-25)
        {
            customerId: 5,
            driverId: 13,
            pickupLocation: 'Bandra West, Mumbai',
            pickupLat: 19.0596,
            pickupLng: 72.8295,
            dropoffLocation: 'Thane, Mumbai',
            dropoffLat: 19.2183,
            dropoffLng: 72.9781,
            vehicleType: 'mini',
            status: 'cancelled',
            fareEstimate: 30.0,
            finalFare: null,
            paymentMethod: 'upi',
            paymentStatus: 'failed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 26 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 26 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
            completionTime: null,
        },
        {
            customerId: 6,
            driverId: 14,
            pickupLocation: 'Connaught Place, New Delhi',
            pickupLat: 28.6315,
            pickupLng: 77.2167,
            dropoffLocation: 'Noida Sector 62',
            dropoffLat: 28.6264,
            dropoffLng: 77.3647,
            vehicleType: 'suv',
            status: 'cancelled',
            fareEstimate: 35.0,
            finalFare: null,
            paymentMethod: 'wallet',
            paymentStatus: 'failed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 27 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 27 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
            completionTime: null,
        },
        {
            customerId: 7,
            driverId: 15,
            pickupLocation: 'Koramangala, Bangalore',
            pickupLat: 12.9352,
            pickupLng: 77.6245,
            dropoffLocation: 'Marathahalli, Bangalore',
            dropoffLat: 12.9591,
            dropoffLng: 77.7014,
            vehicleType: 'auto',
            status: 'cancelled',
            fareEstimate: 10.0,
            finalFare: null,
            paymentMethod: 'cash',
            paymentStatus: 'failed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 28 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 28 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
            completionTime: null,
        },
        {
            customerId: 8,
            driverId: 16,
            pickupLocation: 'Anna Nagar, Chennai',
            pickupLat: 13.0878,
            pickupLng: 80.2085,
            dropoffLocation: 'Ambattur, Chennai',
            dropoffLat: 13.1143,
            dropoffLng: 80.1548,
            vehicleType: 'sedan',
            status: 'cancelled',
            fareEstimate: 14.0,
            finalFare: null,
            paymentMethod: 'card',
            paymentStatus: 'failed',
            bookingTime: new Date(thirtyDaysAgo.getTime() + 29 * 24 * 60 * 60 * 1000).toISOString(),
            pickupTime: new Date(thirtyDaysAgo.getTime() + 29 * 24 * 60 * 60 * 1000 + 18 * 60 * 1000).toISOString(),
            completionTime: null,
        },
    ];

    await db.insert(bookings).values(sampleBookings);
    
    console.log('✅ Bookings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});